//package mssqlxorm
//package xorm
package xormcode

import (
	"./dbmanagers"
	"./models"
	"fmt"
)

func Xorm_init() {
	// parameter false - will not show Sql code generated by ORM
	// Init DB
	dbmanagers.InitDB(false)

	resultDb := dbmanagers.GetCustomers()
	fmt.Printf("There are customers %d in DB \n\n", len(resultDb))
	// Insert Customers
	fmt.Println("------ Init the DB ------------")
}

//func xorm_ins() {
func Xorm_insert(customerObj models.Barfoottable1) {

	insertRes := dbmanagers.InsertCustomer(customerObj)
	fmt.Println("Customer was inserted : ", insertRes)

	//for _, item := range resultDb {
	//	fmt.Println(item.ToString())
	//}
}
