//package mssqlxorm
package xorm

//import "../../config"

import (
	"./dbmanagers"
	"./models"
	"fmt"
)

func xorm_ins() {
	// parameter false - will not show Sql code generated by ORM
	// Init DB
	dbmanagers.InitDB(false)

	resultDb := dbmanagers.GetCustomers()
	fmt.Printf("There are customers %d in DB \n\n", len(resultDb))
	// Insert Customers
	fmt.Println("------ InsertCustomer ------------")

	insertRes := dbmanagers.InsertCustomer(customerObj)
	fmt.Println("Customer was inserted : ", insertRes)

	//	resultDb = dbmanagers.GetCustomers()

	//for _, item := range resultDb {
	//	fmt.Println(item.ToString())
	//}
}
